# Generated by Django 4.1.2 on 2022-11-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Artiste_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='musicapp.artiste'),
        ),
        migrations.AlterField(
            model_name='song',
            name='Likes',
            field=models.IntegerField(null=True),
        ),
    ]
