# Generated by Django 4.1.2 on 2022-11-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_song_artiste_id_alter_song_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
